force-app/main/default/objects/Child_Object__c/Child_Object__c.object-meta.xml
<CustomObject>
    <label>Child Object</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Child Object #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_Object__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Object</label>
    <referenceTo>Parent_Object__c</referenceTo>
    <relationshipLabel>Child Objects</relationshipLabel>
    <relationshipName>Child_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent_Object__c/Parent_Object__c.object-meta.xml
<CustomObject>
    <label>Parent Object</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Parent Object #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChildObjectTriggerHandler.cls
public class ChildObjectTriggerHandler {
    
    public static void RollupToParent(List<Child_Object__c> newList, Map<Id, Child_Object__c> oldMap) {

        Set<Id> parentIds = new Set<Id>();

        if (newList != null && oldMap == null) {
            for (Child_Object__c newChild : newList) {
                if (newChild.Parent_Object__c != null) {
                    parentIds.add(newChild.Parent_Object__c);
                }
            }
        }
        if (newList == null && oldMap != null) {
            for (Child_Object__c oldChild : oldMap.values()) {
                if (oldChild.Parent_Object__c != null) {
                    parentIds.add(oldChild.Parent_Object__c);
                }
            }
        }
        if (newList != null && oldMap != null) {
            for (Child_Object__c newChild : newList) {
                Child_Object__c oldChild = oldMap.get(newChild.Id);
                if (newChild.Parent_Object__c != null) {
                    parentIds.add(newChild.Parent_Object__c);
                }
                if (oldChild.Parent_Object__c != null) {
                    parentIds.add(oldChild.Parent_Object__c);
                }
            }
        }

        if (parentIds.size() > 0) {
            Database.executeBatch(new RollupsBatch(parentIds), 2000);
        }
    }
}